create table if not exists purchase_orders (
    id bigint generated by default as identity primary key,
    order_no varchar(60) not null,
    request_id bigint not null,
    ordered_by varchar(80) not null,
    ordered_at timestamp not null,
    constraint uk_purchase_orders_order_no unique (order_no),
    constraint uk_purchase_orders_request unique (request_id),
    constraint fk_purchase_orders_request foreign key (request_id) references purchase_requests (id)
);
