create table if not exists customers (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(140) not null,
    business_number varchar(40) not null,
    contact_name varchar(80) not null,
    phone varchar(40) not null,
    email varchar(120) not null,
    active boolean not null default true,
    constraint uk_customers_code unique (code),
    constraint uk_customers_business_number unique (business_number)
);

insert into customers (code, name, business_number, contact_name, phone, email, active)
select 'AX-CUS-001', 'Axis 리테일 고객사', '201-88-00001', '김고객', '02-4000-1000', 'retail@axis.local', true
where not exists (select 1 from customers where code = 'AX-CUS-001');

insert into customers (code, name, business_number, contact_name, phone, email, active)
select 'AX-CUS-002', '엔터프라이즈 파트너', '201-88-00002', '박고객', '02-4000-2000', 'enterprise@axis.local', true
where not exists (select 1 from customers where code = 'AX-CUS-002');
