create table if not exists sales_orders (
    id bigint generated by default as identity primary key,
    order_no varchar(60) not null,
    customer_id bigint not null,
    item_id bigint not null,
    quantity integer not null,
    unit_price numeric(15, 2) not null,
    status varchar(30) not null,
    memo varchar(255),
    ordered_by varchar(80) not null,
    ordered_at timestamp not null,
    processed_by varchar(80),
    processed_at timestamp,
    constraint uk_sales_orders_order_no unique (order_no),
    constraint fk_sales_orders_customer foreign key (customer_id) references customers (id),
    constraint fk_sales_orders_item foreign key (item_id) references items (id)
);
