create table if not exists audit_logs (
    id bigint generated by default as identity primary key,
    domain_type varchar(40) not null,
    event_type varchar(80) not null,
    reference_no varchar(120) not null default '',
    summary varchar(255) not null,
    detail varchar(500),
    actor varchar(100) not null,
    occurred_at timestamp not null
);
