create table if not exists departments (
    id bigint generated by default as identity primary key,
    code varchar(40) not null,
    name varchar(100) not null,
    description varchar(255),
    constraint uk_departments_code unique (code)
);

create table if not exists employees (
    id bigint generated by default as identity primary key,
    employee_no varchar(40) not null,
    display_name varchar(100) not null,
    email varchar(120) not null,
    position_title varchar(80) not null,
    status varchar(20) not null,
    department_id bigint not null,
    constraint uk_employees_employee_no unique (employee_no),
    constraint fk_employees_department foreign key (department_id) references departments (id)
);

create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    password varchar(255) not null,
    display_name varchar(100) not null,
    employee_id bigint,
    constraint uk_app_users_username unique (username),
    constraint fk_app_users_employee foreign key (employee_id) references employees (id)
);

create table if not exists app_user_roles (
    user_id bigint not null,
    role varchar(40) not null,
    primary key (user_id, role),
    constraint fk_app_user_roles_user foreign key (user_id) references app_users (id)
);

create table if not exists attendance_records (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    work_date date not null,
    check_in_at timestamp,
    check_out_at timestamp,
    status varchar(30) not null,
    constraint uk_attendance_username_work_date unique (username, work_date)
);
