create table if not exists attendance_settings (
    id bigint generated by default as identity primary key,
    standard_check_in_at time not null,
    standard_check_out_at time not null,
    late_after_at time not null
);

insert into attendance_settings (standard_check_in_at, standard_check_out_at, late_after_at)
select time '09:00:00', time '18:00:00', time '09:10:00'
where not exists (select 1 from attendance_settings);

insert into role_permissions (role, permission)
select role, permission
from (
    select 'SUPER_ADMIN' as role, 'DEPARTMENT_CREATE' as permission
    union all select 'ADMIN', 'DEPARTMENT_CREATE'
    union all select 'HR_MANAGER', 'DEPARTMENT_CREATE'
    union all select 'SUPER_ADMIN', 'ATTENDANCE_SETTINGS_UPDATE'
    union all select 'ADMIN', 'ATTENDANCE_SETTINGS_UPDATE'
    union all select 'HR_MANAGER', 'ATTENDANCE_SETTINGS_UPDATE'
) next_permissions
where not exists (
    select 1
    from role_permissions
    where role_permissions.role = next_permissions.role
      and role_permissions.permission = next_permissions.permission
);
