create table if not exists role_permission_defaults (
    id bigint generated by default as identity primary key,
    role varchar(40) not null,
    permission varchar(80) not null,
    constraint uk_role_permission_defaults_role_permission unique (role, permission)
);
