create table if not exists role_permissions (
    id bigint generated by default as identity primary key,
    role varchar(40) not null,
    permission varchar(80) not null,
    constraint uk_role_permissions_role_permission unique (role, permission)
);
