create table if not exists attendance_change_requests (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    work_date date not null,
    requested_check_in_at time not null,
    requested_check_out_at time not null,
    reason varchar(1000) not null,
    status varchar(30) not null,
    requested_at timestamp not null,
    approved_at timestamp
);
