create table if not exists items (
    id bigint generated by default as identity primary key,
    sku varchar(60) not null,
    name varchar(140) not null,
    category varchar(80) not null,
    unit varchar(20) not null,
    safety_stock integer not null,
    active boolean not null default true,
    constraint uk_items_sku unique (sku)
);

create table if not exists warehouses (
    id bigint generated by default as identity primary key,
    code varchar(40) not null,
    name varchar(100) not null,
    constraint uk_warehouses_code unique (code)
);

create table if not exists inventory_stocks (
    id bigint generated by default as identity primary key,
    item_id bigint not null,
    warehouse_id bigint not null,
    quantity integer not null,
    constraint uk_inventory_stocks_item_warehouse unique (item_id, warehouse_id),
    constraint fk_inventory_stocks_item foreign key (item_id) references items (id),
    constraint fk_inventory_stocks_warehouse foreign key (warehouse_id) references warehouses (id)
);

create table if not exists inventory_movements (
    id bigint generated by default as identity primary key,
    item_id bigint not null,
    warehouse_id bigint not null,
    quantity_delta integer not null,
    reason varchar(255) not null,
    processed_by varchar(80) not null,
    processed_at timestamp not null,
    constraint fk_inventory_movements_item foreign key (item_id) references items (id),
    constraint fk_inventory_movements_warehouse foreign key (warehouse_id) references warehouses (id)
);

insert into warehouses (code, name)
select 'MAIN', '본사 창고'
where not exists (select 1 from warehouses where code = 'MAIN');

insert into warehouses (code, name)
select 'SUB', '보조 창고'
where not exists (select 1 from warehouses where code = 'SUB');

insert into items (sku, name, category, unit, safety_stock, active)
select 'AX-ITM-001', '표준 노트북', 'IT 장비', '대', 5, true
where not exists (select 1 from items where sku = 'AX-ITM-001');

insert into items (sku, name, category, unit, safety_stock, active)
select 'AX-ITM-002', '업무용 모니터', 'IT 장비', '대', 8, true
where not exists (select 1 from items where sku = 'AX-ITM-002');

insert into items (sku, name, category, unit, safety_stock, active)
select 'AX-ITM-003', '사무 소모품 세트', '소모품', '세트', 20, true
where not exists (select 1 from items where sku = 'AX-ITM-003');

insert into inventory_stocks (item_id, warehouse_id, quantity)
select i.id, w.id,
       case
           when i.sku = 'AX-ITM-001' and w.code = 'MAIN' then 12
           when i.sku = 'AX-ITM-002' and w.code = 'MAIN' then 6
           when i.sku = 'AX-ITM-003' and w.code = 'MAIN' then 35
           else 0
       end
from items i
cross join warehouses w
where not exists (
    select 1
    from inventory_stocks s
    where s.item_id = i.id and s.warehouse_id = w.id
);
