create table if not exists suppliers (
    id bigint generated by default as identity primary key,
    code varchar(60) not null,
    name varchar(140) not null,
    business_number varchar(40) not null,
    contact_name varchar(80) not null,
    phone varchar(40) not null,
    email varchar(120) not null,
    active boolean not null default true,
    constraint uk_suppliers_code unique (code),
    constraint uk_suppliers_business_number unique (business_number)
);

create table if not exists purchase_requests (
    id bigint generated by default as identity primary key,
    request_no varchar(60) not null,
    supplier_id bigint not null,
    item_id bigint not null,
    quantity integer not null,
    unit_price numeric(15, 2) not null,
    status varchar(30) not null,
    memo varchar(255),
    requested_by varchar(80) not null,
    requested_at timestamp not null,
    constraint uk_purchase_requests_request_no unique (request_no),
    constraint fk_purchase_requests_supplier foreign key (supplier_id) references suppliers (id),
    constraint fk_purchase_requests_item foreign key (item_id) references items (id)
);

insert into suppliers (code, name, business_number, contact_name, phone, email, active)
select 'AX-SUP-001', 'Axis IT 공급사', '101-88-00001', '김공급', '02-1000-1000', 'it-supply@axis.local', true
where not exists (select 1 from suppliers where code = 'AX-SUP-001');

insert into suppliers (code, name, business_number, contact_name, phone, email, active)
select 'AX-SUP-002', '오피스 소모품 파트너', '101-88-00002', '박파트너', '02-2000-2000', 'office@axis.local', true
where not exists (select 1 from suppliers where code = 'AX-SUP-002');
